<?php
namespace Core\UI\Html;
use Core\Enum;
/**
 * The type of key to be generated by a "keygen" html element
 */
final class KeyTypes extends Enum{
	public static $RSA, $DSA, $EC;
	/** Protected Constructor - instantiates an instance of the enumeration. Used internally only */
	protected function __construct($name, $value){parent::__construct($name, $value);}
	/** Static Constructor */
	public static function Initialize(){
		self::$RSA = new KeyTypes('RSA', 'rsa');
		self::$DSA = new KeyTypes('DSA', 'dsa');
		self::$EC = new KeyTypes('EC', 'ec');
	}
};
KeyTypes::Initialize();
?>