<?php
use Core\Web\Bs as B;
final class BsIcons extends Object{
	private function __construct(){}
	public static function Asterisk($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-asterisk', $title);}
	public static function Plus($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-plus', $title);}
	public static function Euro($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-euro', $title);}
	public static function Eur($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-eur', $title);}
	public static function Minus($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-minus', $title);}
	public static function Cloud($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-cloud', $title);}
	public static function Envelope($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-envelope', $title);}
	public static function Pencil($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-pencil', $title);}
	public static function Glass($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-glass', $title);}
	public static function Music($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-music', $title);}
	public static function Search($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-search', $title);}
	public static function Heart($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-heart', $title);}
	public static function Star($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-star', $title);}
	public static function StarEmpty($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-star-empty', $title);}
	public static function User($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-user', $title);}
	public static function Film($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-film', $title);}
	public static function ThLarge($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-th-large', $title);}
	public static function Th($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-th', $title);}
	public static function ThList($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-th-list', $title);}
	public static function Ok($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-ok', $title);}
	public static function Remove($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-remove', $title);}
	public static function ZoomIn($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-zoom-in', $title);}
	public static function ZoomOut($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-zoom-out', $title);}
	public static function Off($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-off', $title);}
	public static function Signal($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-signal', $title);}
	public static function Cog($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-cog', $title);}
	public static function Trash($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-trash', $title);}
	public static function Home($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-home', $title);}
	public static function File($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-file', $title);}
	public static function Time($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-time', $title);}
	public static function Road($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-road', $title);}
	public static function DownloadAlt($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-download-alt', $title);}
	public static function Download($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-download', $title);}
	public static function Upload($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-upload', $title);}
	public static function Inbox($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-inbox', $title);}
	public static function PlayCircle($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-play-circle', $title);}
	public static function Repeat($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-repeat', $title);}
	public static function Refresh($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-refresh', $title);}
	public static function ListAlt($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-list-alt', $title);}
	public static function Lock($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-lock', $title);}
	public static function Flag($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-flag', $title);}
	public static function Headphones($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-headphones', $title);}
	public static function VolumeOff($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-volume-off', $title);}
	public static function VolumeDown($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-volume-down', $title);}
	public static function VolumeUp($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-volume-up', $title);}
	public static function Qrcode($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-qrcode', $title);}
	public static function Barcode($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-barcode', $title);}
	public static function Tag($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-tag', $title);}
	public static function Tags($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-tags', $title);}
	public static function Book($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-book', $title);}
	public static function Bookmark($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-bookmark', $title);}
	public static function Print_($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-print', $title);}
	public static function Camera($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-camera', $title);}
	public static function Font($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-font', $title);}
	public static function Bold($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-bold', $title);}
	public static function Italic($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-italic', $title);}
	public static function TextHeight($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-text-height', $title);}
	public static function TextWidth($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-text-width', $title);}
	public static function AlignLeft($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-align-left', $title);}
	public static function AlignCenter($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-align-center', $title);}
	public static function AlignRight($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-align-right', $title);}
	public static function AlignJustify($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-align-justify', $title);}
	public static function List_($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-list', $title);}
	public static function IndentLeft($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-indent-left', $title);}
	public static function IndentRight($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-indent-right', $title);}
	public static function FacetimeVideo($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-facetime-video', $title);}
	public static function Picture($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-picture', $title);}
	public static function MapMarker($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-map-marker', $title);}
	public static function Adjust($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-adjust', $title);}
	public static function Tint($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-tint', $title);}
	public static function Edit($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-edit', $title);}
	public static function Share($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-share', $title);}
	public static function Check($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-check', $title);}
	public static function Move($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-move', $title);}
	public static function StepBackward($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-step-backward', $title);}
	public static function FastBackward($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-fast-backward', $title);}
	public static function Backward($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-backward', $title);}
	public static function Play($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-play', $title);}
	public static function Pause($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-pause', $title);}
	public static function Stop($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-stop', $title);}
	public static function Forward($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-forward', $title);}
	public static function FastForward($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-fast-forward', $title);}
	public static function StepForward($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-step-forward', $title);}
	public static function Eject($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-eject', $title);}
	public static function ChevronLeft($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-chevron-left', $title);}
	public static function ChevronRight($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-chevron-right', $title);}
	public static function PlusSign($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-plus-sign', $title);}
	public static function MinusSign($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-minus-sign', $title);}
	public static function RemoveSign($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-remove-sign', $title);}
	public static function OkSign($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-ok-sign', $title);}
	public static function QuestionSign($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-question-sign', $title);}
	public static function InfoSign($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-info-sign', $title);}
	public static function Screenshot($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-screenshot', $title);}
	public static function RemoveCircle($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-remove-circle', $title);}
	public static function OkCircle($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-ok-circle', $title);}
	public static function BanCircle($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-ban-circle', $title);}
	public static function ArrowLeft($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-arrow-left', $title);}
	public static function ArrowRight($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-arrow-right', $title);}
	public static function ArrowUp($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-arrow-up', $title);}
	public static function ArrowDown($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-arrow-down', $title);}
	public static function ShareAlt($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-share-alt', $title);}
	public static function ResizeFull($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-resize-full', $title);}
	public static function ResizeSmall($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-resize-small', $title);}
	public static function ExclamationSign($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-exclamation-sign', $title);}
	public static function Gift($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-gift', $title);}
	public static function Leaf($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-leaf', $title);}
	public static function Fire($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-fire', $title);}
	public static function EyeOpen($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-eye-open', $title);}
	public static function EyeClose($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-eye-close', $title);}
	public static function WarningSign($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-warning-sign', $title);}
	public static function Plane($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-plane', $title);}
	public static function Calendar($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-calendar', $title);}
	public static function Random($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-random', $title);}
	public static function Comment($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-comment', $title);}
	public static function Magnet($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-magnet', $title);}
	public static function ChevronUp($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-chevron-up', $title);}
	public static function ChevronDown($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-chevron-down', $title);}
	public static function Retweet($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-retweet', $title);}
	public static function ShoppingCart($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-shopping-cart', $title);}
	public static function FolderClose($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-folder-close', $title);}
	public static function FolderOpen($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-folder-open', $title);}
	public static function ResizeVertical($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-resize-vertical', $title);}
	public static function ResizeHorizontal($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-resize-horizontal', $title);}
	public static function Hdd($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-hdd', $title);}
	public static function Bullhorn($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-bullhorn', $title);}
	public static function Bell($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-bell', $title);}
	public static function Certificate($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-certificate', $title);}
	public static function ThumbsUp($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-thumbs-up', $title);}
	public static function ThumbsDown($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-thumbs-down', $title);}
	public static function HandRight($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-hand-right', $title);}
	public static function HandLeft($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-hand-left', $title);}
	public static function HandUp($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-hand-up', $title);}
	public static function HandDown($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-hand-down', $title);}
	public static function CircleArrowRight($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-circle-arrow-right', $title);}
	public static function CircleArrowLeft($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-circle-arrow-left', $title);}
	public static function CircleArrowUp($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-circle-arrow-up', $title);}
	public static function CircleArrowDown($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-circle-arrow-down', $title);}
	public static function Globe($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-globe', $title);}
	public static function Wrench($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-wrench', $title);}
	public static function Tasks($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-tasks', $title);}
	public static function Filter($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-filter', $title);}
	public static function Briefcase($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-briefcase', $title);}
	public static function Fullscreen($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-fullscreen', $title);}
	public static function Dashboard($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-dashboard', $title);}
	public static function Paperclip($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-paperclip', $title);}
	public static function HeartEmpty($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-heart-empty', $title);}
	public static function Link($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-link', $title);}
	public static function Phone($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-phone', $title);}
	public static function Pushpin($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-pushpin', $title);}
	public static function Usd($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-usd', $title);}
	public static function Gbp($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-gbp', $title);}
	public static function Sort($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-sort', $title);}
	public static function SortByAlphabet($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-sort-by-alphabet', $title);}
	public static function SortByAlphabetAlt($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-sort-by-alphabet-alt', $title);}
	public static function SortByOrder($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-sort-by-order', $title);}
	public static function SortByOrderAlt($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-sort-by-order-alt', $title);}
	public static function SortByAttributes($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-sort-by-attributes', $title);}
	public static function SortByAttributesAlt($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-sort-by-attributes-alt', $title);}
	public static function Unchecked($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-unchecked', $title);}
	public static function Expand($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-expand', $title);}
	public static function CollapseDown($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-collapse-down', $title);}
	public static function CollapseUp($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-collapse-up', $title);}
	public static function LogIn($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-log-in', $title);}
	public static function Flash($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-flash', $title);}
	public static function LogOut($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-log-out', $title);}
	public static function NewWindow($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-new-window', $title);}
	public static function Record($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-record', $title);}
	public static function Save($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-save', $title);}
	public static function Open($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-open', $title);}
	public static function Saved($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-saved', $title);}
	public static function Import($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-import', $title);}
	public static function Export($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-export', $title);}
	public static function Send($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-send', $title);}
	public static function FloppyDisk($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-floppy-disk', $title);}
	public static function FloppySaved($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-floppy-saved', $title);}
	public static function FloppyRemove($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-floppy-remove', $title);}
	public static function FloppySave($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-floppy-save', $title);}
	public static function FloppyOpen($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-floppy-open', $title);}
	public static function CreditCard($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-credit-card', $title);}
	public static function Transfer($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-transfer', $title);}
	public static function Cutlery($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-cutlery', $title);}
	public static function Header($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-header', $title);}
	public static function Compressed($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-compressed', $title);}
	public static function Earphone($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-earphone', $title);}
	public static function PhoneAlt($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-phone-alt', $title);}
	public static function Tower($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-tower', $title);}
	public static function Stats($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-stats', $title);}
	public static function SdVideo($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-sd-video', $title);}
	public static function HdVideo($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-hd-video', $title);}
	public static function Subtitles($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-subtitles', $title);}
	public static function SoundStereo($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-sound-stereo', $title);}
	public static function SoundDolby($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-sound-dolby', $title);}
	public static function Sound51($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-sound-5-1', $title);}
	public static function Sound61($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-sound-6-1', $title);}
	public static function Sound71($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-sound-7-1', $title);}
	public static function CopyrightMark($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-copyright-mark', $title);}
	public static function RegistrationMark($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-registration-mark', $title);}
	public static function CloudDownload($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-cloud-download', $title);}
	public static function CloudUpload($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-cloud-upload', $title);}
	public static function TreeConifer($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-tree-conifer', $title);}
	public static function TreeDeciduous($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-tree-deciduous', $title);}
	public static function Cd($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-cd', $title);}
	public static function SaveFile($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-save-file', $title);}
	public static function OpenFile($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-open-file', $title);}
	public static function LevelUp($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-level-up', $title);}
	public static function Copy($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-copy', $title);}
	public static function Paste($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-paste', $title);}
	public static function Alert($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-alert', $title);}
	public static function Equalizer($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-equalizer', $title);}
	public static function King($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-king', $title);}
	public static function Queen($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-queen', $title);}
	public static function Pawn($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-pawn', $title);}
	public static function Bishop($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-bishop', $title);}
	public static function Knight($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-knight', $title);}
	public static function BabyFormula($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-baby-formula', $title);}
	public static function Tent($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-tent', $title);}
	public static function Blackboard($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-blackboard', $title);}
	public static function Bed($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-bed', $title);}
	public static function Apple($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-apple', $title);}
	public static function Erase($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-erase', $title);}
	public static function Hourglass($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-hourglass', $title);}
	public static function Lamp($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-lamp', $title);}
	public static function Duplicate($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-duplicate', $title);}
	public static function PiggyBank($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-piggy-bank', $title);}
	public static function Scissors($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-scissors', $title);}
	public static function Bitcoin($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-bitcoin', $title);}
	public static function Btc($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-btc', $title);}
	public static function Xbt($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-xbt', $title);}
	public static function Yen($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-yen', $title);}
	public static function Jpy($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-jpy', $title);}
	public static function Ruble($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-ruble', $title);}
	public static function Rub($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-rub', $title);}
	public static function Scale($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-scale', $title);}
	public static function IceLolly($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-ice-lolly', $title);}
	public static function IceLollyTasted($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-ice-lolly-tasted', $title);}
	public static function Education($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-education', $title);}
	public static function OptionHorizontal($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-option-horizontal', $title);}
	public static function OptionVertical($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-option-vertical', $title);}
	public static function MenuHamburger($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-menu-hamburger', $title);}
	public static function ModalWindow($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-modal-window', $title);}
	public static function Oil($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-oil', $title);}
	public static function Grain($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-grain', $title);}
	public static function Sunglasses($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-sunglasses', $title);}
	public static function TextSize($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-text-size', $title);}
	public static function TextColor($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-text-color', $title);}
	public static function TextBackground($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-text-background', $title);}
	public static function ObjectAlignTop($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-object-align-top', $title);}
	public static function ObjectAlignBottom($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-object-align-bottom', $title);}
	public static function ObjectAlignHorizontal($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-object-align-horizontal', $title);}
	public static function ObjectAlignLeft($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-object-align-left', $title);}
	public static function ObjectAlignVertical($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-object-align-vertical', $title);}
	public static function ObjectAlignRight($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-object-align-right', $title);}
	public static function TriangleRight($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-triangle-right', $title);}
	public static function TriangleLeft($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-triangle-left', $title);}
	public static function TriangleBottom($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-triangle-bottom', $title);}
	public static function TriangleTop($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-triangle-top', $title);}
	public static function Console($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-console', $title);}
	public static function Superscript($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-superscript', $title);}
	public static function Subscript($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-subscript', $title);}
	public static function MenuLeft($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-menu-left', $title);}
	public static function MenuRight($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-menu-right', $title);}
	public static function MenuDown($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-menu-down', $title);}
	public static function MenuUp($id='', $title=''){return new HtmlSpanElement('', $id, 'glyphicon glyphicon-menu-up', $title);}
};
?>